### ISSUE TITLE
CI에서 manylinux로 빌드 및 pip에 배포

### ISSUE THREAD

**Issue by furiosamg** [furiosa-ai/furiosa-models#19]
작업했었던 github workflow 일부를 남겨놓습니다.

```yaml
env:
  PACKAGE_NAME: furiosa_models
###
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        default: true
    - name: Build Wheels
      uses: messense/maturin-action@v1
      with:
        manylinux: auto
        args: -i ${{ matrix.python-version }} --release --out dist
###
        pip install dist/${{ env.PACKAGE_NAME }}-*.whl --force-reinstall
```
