### ISSUE TITLE
PyO3과련 기존 레이아웃 변경 Rollback 논의: python/furiosa/models --> furiosa/models

### ISSUE THREAD

**Issue by hyeokjunejeon** [furiosa-ai/furiosa-models#25]
@furiosamg 님, @hyunsik 님,

제가 테스트 해본 결과
기존 레이아웃 방식이 잘 진행되고 테스트도 잘 되었습니다.
예를들면, furiosa.__init__.py 를 생성하지 않아도 됩니다.

PyO3 문서에 따르면(https://maturin.rs/project_layout.html#alternate-python-source-directory-src-layout)가 python 폴더를 만들라는 것도 아닌 듯합니다.

``` toml
[package]
name = "furiosa-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "furiosa_models_native"
crate-type = ["cdylib"]

# https://maturin.rs/project_layout.html#alternate-python-source-directory-src-layout
[package.metadata.maturin]
python-source = "furiosa/models"
name = "furiosa.models.furiosa_models_native"

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
```

# Test code
pip install -e .

```python
from furiosa.models import sum_as_string
sum_as_string(1,2)
```

_Originally posted by @hyeokjunejeon in https://github.com/furiosa-ai/furiosa-models-experimental/issues/10#issuecomment-1220545654_
